### ISSUE TITLE
failure TypeError: facility.links is not iterable

### ISSUE THREAD

**Issue by ad-okshaj** [autodesk-tandem/tutorial-rest#39]
Hi,

Error Code:

failure TypeError: facility.links is not iterable
    at main (file:///C:/Users/Adokshaj/OneDrive%20-%20Sclera/Documents/Folder%20to%20test%20out%20Tandem%20JS%20REST%20API%20Code/assets/read-asset-properties.js:28:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    
IDE Used:

WebStorm
Version: 2024.2.3
Build: 242.23339.15
26 September 2024

Steps to reproduce:

1. Replace 'APS_CLIENT_ID', 'APC_CLIENT_SECRET', 'FACILITY_URN' is the code
2. Run read-asset-properties.js file

**Comment by liskaj** [comment]
Hello, is there any model in your facility, pls? There is missing check if `facility.links` is not null - I'll fix this.

**Comment by liskaj** [comment]
Did you add your APS application (Client ID) to your facility, pls? This is needed to access facility data using API. Note that your can add APS app either on facility level or on account level. When added on account level then your APS app will have access to all facilities.

![image](https://github.com/user-attachments/assets/041003a6-4583-41c1-8fe4-f0104be3269f)

**Comment by ad-okshaj** [comment]
Thank you @liskaj. The issue is solved.

Adding APS Client ID to our facility using your method solved this issue.
